groups:
  - name: cje
    rules:
    - alert: JenkinsPluginsWaitingForUpdate
      expr: jenkins_plugins_withUpdate > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Jenkins - pending plugins updates
        description: "{{$labels.instance}} have pending updates - {{ $value }} plugins have updates"

    - alert: JenkinsBuildQueueWaringLevel
      expr: jenkins_queue_size_value > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Jenkins Build Queue have 5 or more items
        description: "Build Queue on {{$labels.instance}} is now {{ $value }}"

    - alert: JenkinsBuildQueueErrorLevel
      expr: jenkins_queue_size_value > 10
      for: 10m
      labels:
        severity: error
      annotations:
        summary: Jenkins Build Queue have 10 or more items
        description: "Build Queue on {{$labels.instance}} is now {{ $value }}"

    - alert: JenkinsLastBuildFailed
      expr: default_jenkins_builds_last_build_result_ordinal{jenkins_job=~".*jablonsk.*", repo="NA"} == 2
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Jenkins last build failed (instance {{ $labels.instance }})
        description: "Last build failed: {{$labels.jenkins_job}}. Failed build for job `{{$labels.jenkins_job}}` on {{$labels.instance}}/{{$labels.env}} ({{$labels.region}})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


    # * RUNNING  -1 true  - The build had no errors.
    # * SUCCESS   0 true  - The build had no errors.
    # * UNSTABLE  1 true  - The build had some errors but they were not fatal. For example, some tests failed.
    # * FAILURE   2 false - The build had a fatal error.
    # * NOT_BUILT 3 false - The module was not built.
    # * ABORTED   4 false - The build was manually aborted.